services:
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "6080:6080"
    depends_on:
      - user-service
      - tracker-service
      - scraper-service
      - ai-matching-service
      - notification-service

  scraper-service:
    build: ./services/scraper-service
    ports:
      - "6081:6081"
    env_file:
      - .env
    depends_on:
    - mongodb
    - redis

  ai-matching-service:
    build: ./services/ai-matching-service
    ports:
      - "6082:6082"
    env_file:
      - .env
    depends_on:
    - mongodb
    - redis
    volumes:
    - uploads_data:/app/uploads

  notification-service:
    build: ./services/notification-service
    ports:
      - "6083:6083"
    env_file:
      - .env
    depends_on:
      - rabbitmq

  user-service:
    build: ./services/user-service
    ports:
      - "6084:6084"
    env_file:
      - .env
    volumes:
    - uploads_data:/app/uploads
  tracker-service:
    build: ./services/tracker-service
    ports:
      - "6085:6085"
    env_file:
      - .env
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mongo_data:
  uploads_data: